FileDescriptorProto{name =
                      Just "examples/definitions/actions.proto",
                    package = Just "actions", dependency = fromList [],
                    public_dependency = fromList [], weak_dependency = fromList [],
                    message_type =
                      fromList
                        [DescriptorProto{name = Just "Unit", field = fromList [],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Active",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "groups",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REPEATED,
                                                                   type' = Just TYPE_INT32,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Controls",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "brakes",
                                                                   number = Just 1,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Unit",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "active",
                                                                   number = Just 2,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Active",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl =
                                           fromList
                                             [OneofDescriptorProto{name = Just "controls",
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         options = Nothing, reserved_range = fromList [],
                                         reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Build",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "foo",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_INT32,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Action",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "controls",
                                                                   number = Just 1,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Controls",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "build",
                                                                   number = Just 2,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Build",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl =
                                           fromList
                                             [OneofDescriptorProto{name = Just "action",
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         options = Nothing, reserved_range = fromList [],
                                         reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])}],
                    enum_type = fromList [], service = fromList [],
                    extension = fromList [], options = Nothing,
                    source_code_info = Nothing, syntax = Nothing,
                    unknown'field = UnknownField (fromList [])}