FileDescriptorProto{name = Just "examples/definitions/ship.proto",
                    package = Just "ship", dependency = fromList ["actions.proto"],
                    public_dependency = fromList [], weak_dependency = fromList [],
                    message_type =
                      fromList
                        [DescriptorProto{name = Just "Vessel",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "width",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "length",
                                                                   number = Just 2,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "FuelTank",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "radius",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "length",
                                                                   number = Just 2,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Engine",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "radius",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "length",
                                                                   number = Just 2,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "group",
                                                                   number = Just 3,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_INT32,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Part",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "vessel",
                                                                   number = Just 1,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Vessel",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "fuelTank",
                                                                   number = Just 2,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "FuelTank",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "engine",
                                                                   number = Just 3,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Engine",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl =
                                           fromList
                                             [OneofDescriptorProto{name = Just "part",
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         options = Nothing, reserved_range = fromList [],
                                         reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Beam",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "length",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Root", field = fromList [],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Attach",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "location",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "rotation",
                                                                   number = Just 2,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "StructureNode",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "beam",
                                                                   number = Just 1,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Beam",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "part",
                                                                   number = Just 2,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Part",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl =
                                           fromList
                                             [OneofDescriptorProto{name = Just "node",
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         options = Nothing, reserved_range = fromList [],
                                         reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "StructureLink",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "root",
                                                                   number = Just 1,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Root",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "attach",
                                                                   number = Just 2,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "Attach",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl =
                                           fromList
                                             [OneofDescriptorProto{name = Just "link",
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         options = Nothing, reserved_range = fromList [],
                                         reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "StructureTree",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "node",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Nothing,
                                                                   type_name = Just "StructureNode",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "link",
                                                                   number = Just 2,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Nothing,
                                                                   type_name = Just "StructureLink",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "EndMarker", field = fromList [],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "StructureData",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "marker",
                                                                   number = Just 1,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "EndMarker",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "tree",
                                                                   number = Just 2,
                                                                   label = Just LABEL_OPTIONAL,
                                                                   type' = Nothing,
                                                                   type_name = Just "StructureTree",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Just 0,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl =
                                           fromList
                                             [OneofDescriptorProto{name = Just "structure",
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         options = Nothing, reserved_range = fromList [],
                                         reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Structure",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "attachments",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REPEATED,
                                                                   type' = Nothing,
                                                                   type_name = Just "StructureData",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "PhysicsState",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "x", number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "y", number = Just 2,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "theta",
                                                                   number = Just 3,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "vx",
                                                                   number = Just 4,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "vy",
                                                                   number = Just 5,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "omega",
                                                                   number = Just 6,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_DOUBLE,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])},
                         DescriptorProto{name = Just "Ship",
                                         field =
                                           fromList
                                             [FieldDescriptorProto{name = Just "entityId",
                                                                   number = Just 1,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Just TYPE_UINT64,
                                                                   type_name = Nothing,
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "structure",
                                                                   number = Just 2,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Nothing,
                                                                   type_name = Just "Structure",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "physicsState",
                                                                   number = Just 3,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Nothing,
                                                                   type_name = Just "PhysicsState",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])},
                                              FieldDescriptorProto{name = Just "active",
                                                                   number = Just 4,
                                                                   label = Just LABEL_REQUIRED,
                                                                   type' = Nothing,
                                                                   type_name =
                                                                     Just "actions.Active",
                                                                   extendee = Nothing,
                                                                   default_value = Nothing,
                                                                   oneof_index = Nothing,
                                                                   json_name = Nothing,
                                                                   options = Nothing,
                                                                   unknown'field =
                                                                     UnknownField (fromList [])}],
                                         extension = fromList [], nested_type = fromList [],
                                         enum_type = fromList [], extension_range = fromList [],
                                         oneof_decl = fromList [], options = Nothing,
                                         reserved_range = fromList [], reserved_name = fromList [],
                                         unknown'field = UnknownField (fromList [])}],
                    enum_type = fromList [], service = fromList [],
                    extension = fromList [], options = Nothing,
                    source_code_info = Nothing, syntax = Nothing,
                    unknown'field = UnknownField (fromList [])}